framework:
    mailer:
        transports:
            main: '%env(MAILER_DSN)%'
            mailhog: 'smtp://mailhog:1025'
            gmail: '%env(GMAIL_DSN)%'

when@test:
    framework:
        mailer:
            transport: 'null://null' 