# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        info:
            title: Study-On.Billing
            description: Пожалуйста работай
            version: 1.0.0
        paths:
            /api/v1/auth:
                post:
                    summary: Авторизация пользователя
                    description: Получение JWT токена по почте и паролю
                    tags:
                        - Авторизация
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        email:
                                            type: string
                                            example: maxim@bk.ru      # <-- Исправленный пример
                                        password:
                                            type: string
                                            example: 1234567         # <-- Исправленный пример
                                    required: [username, password]
                    responses:
                        '200':
                            description: Успешная авторизация
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                                            refresh_token:
                                                type: string
                                                exambple: "fgfdgJhbGciOiJdfgfdgIkpXVCJ9..."
                        '401':
                            description: Неверные учетные данные     # <-- Исправлено описание
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            code: 
                                                type: integer
                                                example: 401
                                            message:
                                                type: string
                                                example: "Invalid credentials."
            /api/v1/refresh:
                post:
                    summary: Обновление JWT токена с помощью refresh токена
                    description: Получение нового JWT и refresh токенов по старому refresh токену
                    tags:
                        - Авторизация
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    type: object
                                    required: [refresh_token]         # <-- исправлено
                                    properties:
                                        refresh_token:
                                            type: string
                                            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                    responses:
                        '200':
                            description: Токены успешно обновлены
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                                            refresh_token:
                                                type: string
                                                example: "ertyrtrsdfFSDnR5cCI6IkpXVCJ9..."
                        '401':
                            description: Неверный или просроченный refresh токен
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            code:
                                                type: integer
                                                example: 401
                                            message:
                                                type: string
                                                example: "Invalid refresh token."

    areas:
        path_patterns:
            - ^/api(?!/doc$)