security:
    password_hashers:
            App\Entity\User: 'auto'
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: 'auto'
                cost:      15

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        login:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\EmailAuthenticator
            jwt: ~
            json_login:
                check_path: /api/v1/auth
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
  
    access_control:
        - { path: ^/api/v1/register, roles: PUBLIC_ACCESS  }
        - { path: ^/api/v1/auth, roles: PUBLIC_ACCESS  }
        - { path: ^/api/v1/doc, roles: PUBLIC_ACCESS  }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
        
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
