controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
api_login_check:
    path: /api/login_check


nelmio_api_doc:
    path: /api/v1/doc
    controller: nelmio_api_doc.controller.swagger
